### ISSUE TITLE
Not recognizing mic image

### ISSUE THREAD

**Issue by ToJen** [CristiVlad25/voice-input#1]
I saw the video and tried to contribute to it. I got this error a few times:

```
Traceback (most recent call last):
  File "vspeak.py", line 14, in <module>
    root.iconbitmap('microphone.png')
  File "/home/tomisin/anaconda3/lib/python3.5/tkinter/__init__.py", line 1716, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "microphone.png" not defined

```

I tried doing this but still didn't get it to work:

```
import sys, os

program_directory = sys.path[0]

root = Tk()                              
root.title('Voice Input')
# root.iconbitmap('mic.ico')

"""solution 1 """
# img = PhotoImage(file='mic.ico')
# root.tk.call('wm', 'iconphoto', root._w, img)

"""solution 2 """
# root.iconphoto(True, PhotoImage(file=os.path.join(program_directory, 'microphone.png')))

```

**Comment by CristiVlad25** [comment]
Traceback (most recent call last):
  File "vspeak.py", line 14, in <module>
    root.iconbitmap('microphone.png')
  File "/home/tomisin/anaconda3/lib/python3.5/tkinter/__init__.py", line 1716, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "microphone.png" not defined

you call the .ico not .png file on the root.iconbitmap. so:

root.iconbitmap('mic.ico') 

and make sure you have the file in the same folder.

**Comment by ToJen** [comment]
Yup, that was the default and this was the error(without editing anything):

```
Traceback (most recent call last):
  File "vspeak.pyw", line 14, in <module>
    root.iconbitmap('mic.ico')
  File "/home/tomisin/anaconda3/lib/python3.5/tkinter/__init__.py", line 1716, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "mic.ico" not defined

```

The mic.ico is in the same file, just cloned from your repo.

**Comment by CristiVlad25** [comment]
as you can see in the top of the app, Im specifying/requesting python 3.4 (default, not anaconda or other variation) to be used. It may be that the methods of the 3.5 you are using may be incompatible with the ones for 3.4

this should clarify things.
